### ISSUE TITLE
local filesystem wont load

### ISSUE THREAD

**Issue by yangandrea** [Davilarek/Vencord#21]
### Content

I downloaded some plugins from betterdiscord I put them and I used the canary version of discord after I restarted the pc the filesystem decided not to load them anymore. The error is also present in the stable version.

and the error is 
fileSystemViewer.tsx:186 This error probably indicates filesystem breakage... TypeError: t.readdirSync is not a function
    at i (utils.ts:401:30)
    at Object.getDirectorySize (utils.ts:415:9)
    at fileSystemViewer.tsx:184:50
    at A8 (fileSystemViewer.tsx:189:25)
    at aA (web.03af5afc37653c7a81c6.js:12:992916)
    at l (web.03af5afc37653c7a81c6.js:12:1048152)
    at ok (web.03af5afc37653c7a81c6.js:12:1031147)
    at web.03af5afc37653c7a81c6.js:12:1031013
    at oG (web.03af5afc37653c7a81c6.js:12:1031021)
    at oO (web.03af5afc37653c7a81c6.js:12:1026058)

### Request Agreement

- [X] I have read the requirements for opening an issue above

**Comment by Davilarek** [comment]
Yes, I'm aware of this issue. It's related to the default cors proxy that was used for fetching remote resources got rate limited/taken down by Cloudflare.
A fix/workaround is to simply change the cors proxy url to another cors proxy url, as the default is just an example.

**Comment by yangandrea** [comment]
ok ill wait a fix

**Comment by yangandrea** [comment]
thanks for the link i put one and it works
