### ISSUE TITLE
YABDP4Nitro Failed to Start

### ISSUE THREAD

**Issue by trapgod1** [Davilarek/Vencord#22]
### Content

YABDP4Nitro has removed dependency on ZeresPluginLibrary
Plugin unable to start now

Log
```
Failed to start YABDP4Nitro
 TypeError: Cannot read properties of undefined (reading 'info')
    at YABDP4Nitro.start (YABDP4Nitro.plugin.js:2750:16)
    at Object.f (pluginConstructor.ts:323:23)
    at Object.<anonymous> (index.ts:227:15)
    at na (pluginConstructor.ts:428:29)
    at index.ts:498:21
  
```

### Request Agreement

- [X] I have read the requirements for opening an issue above

**Comment by Davilarek** [comment]
Huh since when BdApi has built-in Logger? uhhh I guess, thanks for reporting will fix in 3 minutes

**Comment by Davilarek** [comment]
Should be fixed now with a4733c198ab7e8bfad70d1e5684bdb2de930ac38

**Comment by trapgod1** [comment]
Plugin Starts now ty
settings panel unable to open 

```
Uncaught TypeError: UI.buildSettingsPanel is not a function
    at YABDP4Nitro.getSettingsPanel (YABDP4Nitro.plugin.js:243:19)
    at yD (pluginConstructor.ts:130:34)
    at onClick (pluginConstructor.ts:212:38)
    at Object.eY (web.e0be055307495f05a833.js:12:1272403)
    at eX (web.e0be055307495f05a833.js:12:1272557)
    at eJ (web.e0be055307495f05a833.js:12:1272614)
    at rb (web.e0be055307495f05a833.js:12:1293695)
    at ry (web.e0be055307495f05a833.js:12:1294111)
    at web.e0be055307495f05a833.js:12:1299014
    at o9 (web.e0be055307495f05a833.js:12:1364414)
    
```

Plugins Fails to Stop

```
Failed to stop YABDP4Nitro
 TypeError: BdApi.unlinkJS is not a function
    at YABDP4Nitro.stop (YABDP4Nitro.plugin.js:2819:15)
    at Object.v (pluginConstructor.ts:329:23)
    at index.ts:273:15
    at eu.<computed> [as apply] (lazy.ts:56:50)
    at u (index.tsx:129:37)
    at onChange (Switch.tsx:72:36)
    at Object.eY (web.e0be055307495f05a833.js:12:1272403)
    at eX (web.e0be055307495f05a833.js:12:1272557)
    at eJ (web.e0be055307495f05a833.js:12:1272614)
    at rb (web.e0be055307495f05a833.js:12:1293695)
    
```

**Comment by Davilarek** [comment]
yeah that's a side effect of deprecating zlib, now I have to implement everything manually... Anyway I will do that in a sec

**Comment by Davilarek** [comment]
the plugin should now stop, but I'm still working on the settings panel

**Comment by Davilarek** [comment]
Should be mostly working as of 3eb5cb500803b303a2102c24641da49fdb965598

**Comment by Davilarek** [comment]
@trapgod1 could you check and confirm if it functions properly now?

**Comment by trapgod1** [comment]
> [@trapgod1](https://github.com/trapgod1) could you check and confirm if it functions properly now?

all features work now, ty

**Comment by Davilarek** [comment]
Thanks

**Comment by trapgod1** [comment]
new function as been added, plugin doesnt work without

```
YABDP4Nitro.plugin.js:3031 TypeError: Webpack.getMangled is not a function
    at eval (YABDP4Nitro.plugin.js:38:31)
    at eval (YABDP4Nitro.plugin.js:3032:17)
    at eval (<anonymous>)
    at WD (pluginConstructor.ts:409:28)
    at us (pluginConstructor.ts:234:23)
    at jd (utils.ts:218:9)

```

**Comment by Davilarek** [comment]
Could you try now? @trapgod1

**Comment by trapgod1** [comment]
```
YABDP4Nitro.plugin.js:3031 TypeError: Webpack.Filters.byPrototypeKeys is not a function
    at eval (YABDP4Nitro.plugin.js:52:57)
    at eval (YABDP4Nitro.plugin.js:3032:17)
    at eval (<anonymous>)
    at WD (pluginConstructor.ts:409:28)
    at us (pluginConstructor.ts:234:23)
    at jd (utils.ts:218:9)
```

**Comment by Davilarek** [comment]
I added byPrototypeKeys with 9d3b5002

**Comment by Davilarek** [comment]
Should start correctly now @trapgod1

**Comment by trapgod1** [comment]
plugin starts and emotes work now but, screenshare is broken

```
utils.ts:63 YABDP4Nitro TypeError: UI.showChangelogModal is not a function
    at YABDP4Nitro.start (YABDP4Nitro.plugin.js:2996:20)
    at Object.g (pluginConstructor.ts:323:23)
    at Object.<anonymous> (index.ts:269:15)
    at ia (pluginConstructor.ts:428:29)
    at utils.ts:219:13
```
```
YABDP4Nitro Error occurred during customVideoSettings() TypeError: Cannot read properties of undefined (reading '3')
```

**Comment by Davilarek** [comment]
I added a dummy showChangelogModal but idk what about the screenshare error, seems like something outside of BV issue can't tell for sure
